customer:
  admin:
    username: ${ADMIN_USERNAME}
    password: ${ADMIN_PASSWORD}
    email: ${ADMIN_EMAIL}
    firstname: ${ADMIN_FIRSTNAME}
    lastname: ${ADMIN_LASTNAME}


app:
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}
  azure:
    client-id: ${AZURE_CLIENT_ID}
    client-secret: ${AZURE_CLIENT_SECRET}
    tenant-id: ${AZURE_TENANT_ID}
    service-principal: ${AZURE_SERVICE_PRINCIPAL}
