security:
  oauth2:
    client:
      scope: password
      client-id: test-client-id
      client-secret: test-client-secret

customer:
  admin:
    username: admin
    password: admin
    email: admin@teste.com
    firstname: Sysadmin
    lastname: Sysadmin

azure:
  app:
    client-id: <azure-client-id>
    client-secret: <azure-client-secret>
    tenant-id: <azure-tenant-id>
    service-principal: <azure-service-principal>

