customer:
  admin:
    username: ${ADMIN_USERNAME}
    password: ${ADMIN_PASSWORD}
    email: ${ADMIN_EMAIL}
    fullName: ${ADMIN_FULLNAME}
    extraInfo: ${ADMIN_EXTRAINFO}

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

app:
  remove-log-after-days: ${REMOVE_LOG_AFTER_DAYS:90}
  url: ${APP_URL}
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}
  azure:
    client-id: ${AZURE_CLIENT_ID}
    client-secret: ${AZURE_CLIENT_SECRET}
    tenant-id: ${AZURE_TENANT_ID}
    service-principal: ${AZURE_SERVICE_PRINCIPAL}
