spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

customer:
  admin:
    username: admin
    password: admin
    email: admin@teste.com
    fullname: Sysadmin
    extraInfo: System Admin

app:
  remove-log-after-days: 90
  url: http://localhost:8081/
  azure:
    client-id: azure_client_id
    client-secret: azure_client_secret
    tenant-id: azure_tenant_id
