customer:
  admin:
    username: admin
    password: admin
    email: admin@teste.com
    firstname: Sysadmin
    lastname: Sysadmin

spring:
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true

app:
  client-id: test-client-id
  client-secret: test-client-secret
  azure:
    client-id: <azure-client-id>
    client-secret: <azure-client-secret>
    tenant-id: <azure-tenant-id>
    service-principal: <azure-service-principal>

