spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/inova
    username: postgres
    password: postgres

customer:
  admin:
    username: admin
    password: admin
    email: admin@teste.com
    fullname: Sysadmin
    extraInfo: System Admin

app:
  remove-log-after-days: ${REMOVE_LOG_AFTER_DAYS:90}
  url: <frontend-url>
  azure:
    client-id: <azure-client-id>
    client-secret: <azure-client-secret>
    tenant-id: <azure-tenant-id>
